config/routes.rb
Bendeveloping::Application.routes.draw do

  root :to => "pages#index"
  
  resources :posts
  resources :messages
  resources :sessions

  get 'login', :controller => 'sessions', :action => 'new'
  get 'logout', :controller => 'sessions', :action => 'destroy'

  get "resume",   :to => "pages#resume"
  get "background",    :to => "pages#background"
  get "projects", :to => "pages#projects"

  match ':not_found' => 'pages#index', :constraints => { :not_found => /.*/ }, :via => 'get'

  

end

app/models/message.rb
class Message
  include ActiveAttr::Model

  attribute :name
  attribute :email
  attribute :message

  validates_presence_of :name, :message
  validates_format_of :email, :multiline => true, :with =>  /^[-a-z0-9_+\.]+\@([-a-z0-9]+\.)+[a-z0-9]{2,4}$/i
  validates_length_of :message, :maximum => 1000
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_permalink
  validates_presence_of :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :admin?

  protected

  def authorize
    unless admin?
      flash[:error] = "unauthorized access"
      redirect_to root_path
      false
    end
  end

  def admin?
    session[:password] == ENV["BLOG_PASSWORD"]
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    if @message.valid?
      MessageMailer.contact_message(@message).deliver
      redirect_to root_url, notice: "Message sent! Thank you for contacting me, #{@message.name}, I'll get back to you shortly."
        else
      render "new"

    end
  end
end      

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @posts = Post.order("created_at DESC")
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, :except => [ :show ]

  def index
    @posts = Post.order("created_at DESC")
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    
    def set_post
      @post = Post.find_by_permalink(params[:id])
    end

  
    def post_params
      params.require(:post).permit(:title, :body)
    end

    def authenticate
      authenticate_or_request_with_http_basic do |name, password|
        name == ENV["USERNAME"] && password == ENV["PASSWORD"]
      end
    end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if params[:password] == ENV["BLOG_PASSWORD"]
      session[:password] = params[:password]
      flash[:notice] = "Successfully logged in"
      redirect_to root_path
    else
      flash[:error] = "Incorrect password"
      render "new"
    end
  end
  
  def destroy
    reset_session
    flash[:notice] = "Successfully logged out"
    redirect_to login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_date(date)
    date.strftime("%B %-d, %Y")
  end

  def post_date(date)
    date.strftime("%m/%-d/%Y %l:%M %P")
  end

  def get_tweet
    tweets = []
    Twitter.user_timeline("bendeveloping").each do |tweet|
      tweets << tweet if tweet.text =~ /#upto/
    end
    @tweet = tweets.first
  end

  def scrub_upto_hashtag(text)
    text.gsub(/\s#upto/, "")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
<div class="header">
  <h2><%= link_to 'bendeveloping', root_path, :class => 'brand' %></h2>
</div>

<div class="header-nav">
  <ul>
    <li><%= link_to 'blog', root_path %> </li>
    <li><%= link_to 'résumé', resume_path %></li>
    <li><%= link_to 'projects', projects_path %></li>
    <li><%= link_to 'about me', background_path %></li>  
    <li><%= link_to 'contact', new_message_path %></li>        
  </ul>    
</div>

<% if admin? %>
  <div class="admin">
    <%= link_to 'logout', logout_path %>
  </div>
<% end %>

app/views/layouts/_links.html.erb
<ul class="links">
  <li><h4>Ben Feldman</h4>Oakland, CA USA</li>
  <li>Full stack web developer specializing in Ruby, Rails, javascript & jQuery; former product manager.</li>
  <li>
    <%= link_to raw("<i class='fa fa-twitter-square fa-2x'></i>"), 'http://twitter.com/bendeveloping' %> <%= link_to raw("<i class='fa fa-github-square fa-2x'></i>"), 'http://github.com/anymd' %> <%= link_to raw("<i class='fa fa-linkedin-square fa-2x'></i>"), 'http://linkedin.com/in/benfeldman' %>
  </li>
  <li><div class="upto-sidebar">
  <i class="fa fa-twitter fa-lg"></i> <b>WHAT I'M UP TO</b><br>
  <%= auto_link(scrub_upto_hashtag(get_tweet.text).html_safe) %>
</div></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <title><%= content_for?(:title) ? yield(:title) : "Ben Developing" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=PT+Serif:400,700,400italic' rel='stylesheet' type='text/css'>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.0/css/font-awesome.css" rel="stylesheet">

    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-45275581-1']);
      _gaq.push(['_setDomainName', 'bendeveloping.com']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>

  </head>

<body>

<%= render 'layouts/header' %>

<div class="container">

    <div class="eleven columns content">  

      <% if flash[:notice] %>
        <p class="thanks close"><i class="fa fa-times-circle"></i> <%= flash[:notice] %></p>
      <% end %>
      <% if flash[:error] %>
        <p class="error close"><i class="fa fa-times-circle"></i> <%= flash[:error] %></p>
      <% end %>

      <%= yield %>
    </div>

    <div class="four columns nav offset-by-one">

      <a href="http://twitter.com/bendeveloping"><div class="profile"><i class="fa fa-twitter"></i> Follow me
        <%= image_tag('ben.jpg') %>
      </div></a>

      <%= render "layouts/links" %>

    </div>
  
  </div>

<div class="upto">
  <i class="fa fa-twitter fa-lg"></i>&nbsp;&nbsp;<b>WHAT I'M UP TO: </b>&nbsp;&nbsp;  
  <%= auto_link(scrub_upto_hashtag(get_tweet.text).html_safe) %>
</div>

<footer>
  <p>&copy; 2013 Ben Developing | Built with Rails 4</p>
</footer>

  <%= javascript_include_tag "application" %>

</body>

</html>

app/views/messages/new.html.erb
<h1>Contact me</h1>

<%= form_for @message do |f| %>
  <% if @message.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being sent:</h2>
      <ul class="bullets">
        <% @message.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>    
  <div class="actions"><%= f.submit "Send Message" %></div>
<% end %>

app/views/pages/background.html.erb
<h1>My Background</h1>


<p></p>
<p>I love technology, always have.  I bought my first computer, an <%= link_to "Atari 800", "http://oldcomputers.net/atari800.html" %>, in 1983 with Bar Mitzvah money.  I still have it and used it to build this web site.  Just kidding.</p>
<p>As a young teen, I spent hundreds of hours typing in programs from computing magazines and was amazed by what was possible.  I had a tape cassette drive for storage and a dot matrix printer that I turned into a scanner using some parts from Radio Shack.</p>
<p>Eventually I got my first external hard drive, a Rana 1000, which changed everything. No more waiting five minutes for programs to load! It didn't take long before I got my first 300 baud modem and was dialing into BBS's to swap games and communicate with strangers.</p>
<p>Although I pursued a degree in the humanities, my first job out of college was with a small software company called Gnossos Software.  It was 1993.  My roommate at the time was working in the White House (Clinton administration) and gave me a tour of the West Wing.  It was there that I saw my first web site - WhiteHouse.gov - running in Netscape. I had been an AOL and Compuserve subscriber for a few years by that point so it all clicked immediately.  I could tell this was something that was going to change the world.</p>
<p>I remember seeing which domain names were available at the time, and if I remember correctly, they were free.  Names like business.com were commonly available.  Had I known how valuable these were to become, well, you know.</p>
<p>I soon taught myself HTML and proposed to my boss that I build our first web site.  It was purely static but I was very proud none-the-less.</p>
<p>Every job I've pursued and had since then has been with small companies creating web-based software and services.  I quickly moved up the product management chain, gaining higher levels of responsibility.  But all along, what really got me excited...where my real passion lied was solving technical problems with the engineers.</p>
<p> I've spend thousands upon thousands of hours working with some amazing engineers, discussing database designs, information architecture, intricate UI details, back-end scaling requirements, integrating with APIs, processing massive amounts of data, providing hooks for future requirements on the product roadmap, you name it.  It was only a matter of time before I got the bug to learn how to code myself.</p>
<p>I've spent years teaching myself various web technologies and have built dozens of web sites.  A few years ago I decided to dive whole hog into learning programming fundamentals and began going through online and offline tutorials.  I attended local meetups.  One of them is called Railsbridge, which is an organization of volunteers who gather monthly to help anyone looking to learn Ruby and Rails.  It was at a Railsbridge meetup that I learned about Dev Bootcamp, an intensive 9-week web development course on programming fundamentals, OOP, databases, front/back-end technologies, APIs, background jobs, AJAX, TDD, pair programming, and all facets of web development.  I applied, got accepted (15% acceptance rate), and attended as soon as they could take me.  It was life changing.</p>
<p>After graduating from Dev Bootcamp, I sought out an apprenticeship to gain some professional development experience.  I landed a three-month gig at Funny Or Die in San Mateo, CA, working with some of the best engineers I've encountered.  This time though, I was not the product manager, I was coding right beside them.  I loved every minute of it and knew I had made the right decision.</p>
<p>Since Funny Or Die I have been working on my own projects, teaching myself new things every day, reading books, attending meetups, blogging, consulting, and looking for full time work. I am very excited for things to come!</p>

app/views/pages/index.html.erb
<% @posts.each do |post| %>
  <% @post = post %>
  <%= render "posts/post" %>  
<% end %>

app/views/pages/projects.html.erb
<h1>My Projects</h1>

<p></p>
<hr>
<h3>Affiliated</h3>

<p>A Rails 4 app I built for a client that allows publishers and marketers to haggle over commission prices with online sellers.  It's an affiliate program that includes a store and integrates with Dwolla payments.  The app is an MVP in order to test out the concept with a few of their clients.  I changed the name of the app and gitignored the config folder so I could put it on Github for prospective employers.</p>
<i class='fa fa-external-link fa-1x'></i>
<%= link_to "app", "https://affiliated.heroku.com", :class => "project-link" %>
<i class='fa fa-github-square fa-1x'></i>
<%= link_to "code", "https://github.com/anymd/affiliated", :class => "project-link"  %>
<p>Gems: bootstrap, devise, dwolla, filepicker, postgres, sass, coffeescript, jquery, rails 4</p>
<hr>

<h3>StaleMikes</h3>
<p>A Rails app and free web service I built that allows communities of working comedians to maintain a list of active comedy shows they can pursue for booking purposes. Every show has a "last verified" date which can be updated by anyone, solving the problem of so many other web sites where show listings get stale very quickly (since shows come and go so frequently).  There are multiple views including a map view built with Google Maps API.</p>
<i class='fa fa-external-link fa-1x'></i>
<%= link_to "app", "http://stalemikes.com", :class => "project-link" %>
<i class='fa fa-github-square fa-1x'></i>
<%= link_to "code", "https://github.com/anymd/stalemikes", :class => "project-link" %>
<p>Gems: gmaps4rails, masonry, filepicker, active_enum, simple_form, sass, jquery, coffeescriptm, onmiauth-facebook, postgres</p>
<hr>

<h3>Devbootstream</h3>
<p>For my final project at Dev Bootcamp, my group of four built out an idea I had to aggregate tweets, tumblr posts and Instagram photos of all Bootcamp students and staff. We incorporated the respective APIs and delivered the posts to the browser in real time using Pusher. We had background jobs running every five minutes (using Sidekiq and Redis) making API requests. For the front end we used Masonry javascript library that mimics the Pinterest layout, plus Infinite Scroll. Posts were memcached for performance. We used Textacular gem for keyword search.</p>
<i class='fa fa-external-link fa-1x'></i>
<%= link_to "app", "http://devbootstream.com", :class => "project-link" %>
<i class='fa fa-github-square fa-1x'></i>
<%= link_to "code", "https://github.com/anymd/bootstream", :class => "project-link" %>
<p>Gems: postgres, omniauth-facebook, instagram, twitter, tweetstream, newrelic, memcache, tumblr, sidekiq, redis, textacular, pusher</p>
<hr>

<h3>Bendeveloping</h3>
<p>I built my personal blog using Rails 4 and host it on heroku.</p>
<i class='fa fa-external-link fa-1x'></i>
<%= link_to "app", "http://bendeveloping.com", :class => "project-link" %>
<p>Gems user: rails_12factor, unicorn, rails 4, active_attr, has_permalink</p>
<hr>

<h3>LaffQ</h3>
<p>LaffQ is another web service I built with a business partner that allows working comedians to easily list and promote their performance schedules online.  I did the front-end coding (but NOT the final design, although I made the logo).  It was built in Python using the Django framework.  I no longer own the rights to the code but you can view the service live.</p>
<i class='fa fa-external-link fa-1x'></i>
<%= link_to "app", "http://laffq.com", :class => "project-link" %>
<hr>

<h3>CosmicWish</h3>
<p>CosmicWish was an online service I built with two business partners that allowed users to design their own greeting card to be printed professionally and mailed to a recipient for any occasion, and the personal message included on the card would also be beamed into space via satellite for novelty purposes. <br><br>The service is no longer available online and I no longer have rights to the code but 
<%= link_to "here are some screenshots", "http://benfeldman.carbonmade.com/projects/4926046#7" %>.</p>

app/views/pages/resume.html.erb
<div class="resume">
  <h2>My Résumé</h2>
  <div class="download-resume"><i class="fa fa-download"></i> <%= link_to "Download PDF", "Ben_Feldman_resume.pdf" %></div>
</div>

<h1>Ben Feldman</h1>
<div class="subtitle">Full-stack web developer with rich product management background</div>

<p>Oakland, California USA</p>

<%= button_to 'Contact Me', new_message_path, :method => :get %>


<h3>TECHNICAL SKILLS</h3>
<ul class="bullets">
  <li>Languages: Ruby, JavaScript, HTML5, CSS3</li>
  <li>Frameworks: Rails 3+, Rails 4, jQuery</li>
  <li>Databases: MySQL, Postgres, Sqlite</li>
  <li>Other: OOP, AJAX, JSON, SQL, Git, Agile, Sass, CoffeeScript</li>
</ul>

<h3>SUMMARY OF QUALIFICATIONS</h3>
<ul class="bullets">
  <li>Passionate full­-stack junior web developer and former product manager specializing in Ruby, Rails and JavaScript.</li>
  <li>15 years managing cutting­-edge web-­based B2B and B2C products at lean startups using waterfall and agile methodologies; two of those companies acquired.</li>
  <li>Strong design and UX skills, 15 years coding HTML/CSS for production prototypes.</li>
  <li>Strong database design and SQL skills.</li>
  <li>2 years professional development experience.</li>
</ul>

<h3>PROJECTS</h3>
<ul class="bullets">
  <li><%= link_to 'DevBootstream.com', 'http://devbootstream.com' %>, Social media aggregator for students and alumni  (<%= link_to 'repo', 'http://github.com/anymd/bootstream' %>)</li>
  <li><%= link_to 'StaleMikes.com', 'http://stalemikes.com' %>, Resources for performers  (<%= link_to 'repo', 'http://github.com/anymd/stalemikes' %>)</li>
  <li><%= link_to 'See more of my projects here', projects_path %></li>
</ul>

<h3>WEB DEVELOPMENT EXPERIENCE</h3>

<div class="company">
  <div><h4>Funny Or Die, San Mateo, CA</h4></div>
  <div class="date">Jun - Sep 2013</div>
</div>

<div class="job-title">Web Developer Apprentice</div>
<ul class="bullets">
  <li>Contributed to massive redesign of Rails app including:
    <ul class="bullets">
      <li>Developed scripts and rake tasks to import critical celebrity data into production db from Google spreadsheets.</li>
      <li>Created migrations and updated ActiveRecord associations and validations to support introduction of user “channels”.</li>
      <li>Updated Rails views and Sass to support new responsive design.</li>
    </ul>
</ul>

<div class="company">
  <div><h4>Dev Bootcamp, San Francisco</h4></div>
  <div class="date">Jan - May 2013</div>
</div>

<ul class="bullets">
  <li>Completed intensive 9-week web development course on programming fundamentals, OOP, databases, front/back-end technologies, APIs, background jobs, AJAX, TDD, pair programming, and all facets of web development.</li>
  <li>Final project selected for demo day (devbootstream).</li>
</ul>  

<div class="company">
  <div><h4>Web Development Consulting</h4></div>
  <div class="date">Oct 2010 - Present</div>
</div>

<ul class="bullets">
  <b><i>GrabSent</i></b>
  <li>Lead developer for web service that enables online sellers to set up their own affiliate programs and for marketers to haggle on their commission rates.</li>
  <li>Developed in Rails 4 with bootstrap, Squarespace and Dwolla integration.</li>
</ul>

<ul class="bullets">
  <b><i>CosmicWish</i></b>
  <li>Front­-end developer, designer and co­founder of web service that lets customers design beautiful printed greeting cards online and beam their wishes into the universe.</li>
  <li>Developed in HTML/CSS, Python, Django</li>
</ul>

<ul class="bullets">
  <b><i>LaffQ</i></b>
  <li>Front­-end developer of web service that lets performance artists track and share their performance schedules.</li>
  <li>Developed in HTML/CSS, Python, Django</li>
</ul>

<h3>PRODUCT MANAGEMENT EXPERIENCE</h3>

<div class="company">
  <div><h4>Juice In The City, San Mateo, CA</h4></div>
  <div class="date">Jan - Dec 2011</div>
</div>

<div class="job-title">Product Manager</div>
<ul class="bullets">
  <li>Drove all aspects of product management for a daily deals site catering to mothers.</li>
  <li>Designed critical operations applications from scratch to recruit large virtual sales force and automate and track their sales process; growing sales force from 10 to 300+ in 6 months.</li>
  <li>Managed API integration with Google Deals and SendGrid.</li>
  <li>Built framework for delivery of timely SQL queries for frequent, highly targeted marketing outreach.</li>
</ul>

<div class="company">
  <div><h4>Entrust (Business Signatures), Redwood City, CA</h4></div>
  <div class="date">Jul 2004 - Dec 2008</div>
</div>

<div class="job-title">Director of Product Management</div>
<ul class="bullets">
  <li>Transformed systems monitoring enterprise software application into world­class online banking fraud detection and prevention solution for top­tier banks.</li>
  <li>Designed suite of applications to monitor online banking customer behavior and alert activity that matches customizable fraud rule patterns.</li>
</ul>

<div class="company">
  <div><h4>Active Decisions, San Mateo, CA</h4></div>
  <div class="date">Mar 1999 - Jul 2004</div>
</div>

<div class="job-title">Senior Product Manager</div>
<ul class="bullets">
  <li>Designed and spearheaded development of Active Buyers Guide and supporting operations applications for leading online automated consumer product recommendation engine.</li>
  <li>Designed white label system implemented by dozens of partners, growing user base from 5k to 40 million in 18 months.</li>
</ul>  

<div class="company">
  <div><h4>mBED Software, San Francisco</h4></div>
  <div class="date">Mar 1997 - Feb 1999</div>
  <div class="job-title">Product Marketing Manager</div>
  <ul class="bullets">
    <li>Instituted and executed product marketing processes for popular multimedia web development software.</li>
    <li>Built demos with mBED’s proprietary scripting language.</li>
  </ul>
</div>

<div class="company">
  <div><h4>Gnossos Software, Washington D.C.</h4></div>
  <div class="date">Jan 1994 - Mar 1997</div>
</div>

<div class="job-title">Senior Marketing Manager</div>
<ul class="bullets">
  <li>Formulated and executed marketing strategies for leading political action committee accounting software solution.</li>
  <li>Built company’s first web site.</li>
</ul>

<h3>EDUCATION</h3>
<ul class="bullets">
  <li>Dev Bootcamp, 2013</li>
  <li>Railsbridge 2012-2013</li>
  <li>Ithaca College, 1993 B.A. Politics, Sociology</li>
</ul>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :body, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :body, :class => 'text_area span12', :rows => '10' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), posts_path, :class => 'btn' %>
  </div>
<% end %>


<div class="gist-admin">
  <p><b>Use this code to embed a gist</b></p>
<%= text_area_tag 'gist', 
"<p><script src='
https://gist.github.com/anymd/7209832
.js'></script></p><p class='gist'>If the gist code does not appear above this sentence, please refresh your browser or visit the following link: <a href='
https://gist.github.com/anymd/7209832
'>
https://gist.github.com/anymd/7209832
</a></p>", :size => "70x10" %>
</div>

app/views/posts/_post.html.erb
<div class="post">
  <h2><%= link_to @post.title, @post %></h2>
  <p><b><%= display_date(@post.created_at) %></b></p>
  <p><%= @post.body.html_safe %></p>
</div>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<%= button_to 'New Post', new_post_path, :method => :get %>

<table class="table">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:permalink) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.id, post_path(post) %></td>
        <td><%= post.title %></td>
        <td><%= post.permalink %></td>        
        <td><%= post_date(post.created_at) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_post_path(post), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      post_path(post),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = Post -%>

<%= render "posts/post" %>

    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'bendeveloping'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    

<div class="form-actions">
  <%= link_to 'Back', root_path, :class => 'btn'  %>

  <% if admin? %>      
  <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_post_path(@post), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")), post_path(@post), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger' %>
  <% end %>
</div>